### ISSUE TITLE
only one filter needs to match

### ISSUE THREAD

**Issue by monteslu** [thegecko/webusb#14]
Not sure this is by the spec, or just the chrome implementation, but in chrome you only need to match one of the filters in your filter list.

Perhaps `.every` should be `.some` ?

https://github.com/thegecko/webusb/blob/master/src/usb.ts#L89

**Comment by thegecko** [comment]
I think maybe you are right. Step 5 here:

https://wicg.github.io/webusb/#request-the-usb-permission

Outlines to remove devices if they don't match a filter, therefore they only need to match one :)
