### ISSUE TITLE
data should be optional on device.controlTransferOut()

### ISSUE THREAD

**Issue by monteslu** [thegecko/webusb#15]
for example:  https://github.com/webusb/arduino/blob/gh-pages/demos/serial.js#L48-L53

**Comment by thegecko** [comment]
Thanks for finding this, must have been an oversight.

PR #16 should resolve the issue, but I'd be grateful if you could check it as I have no way of testing it on actual hardware.

**Comment by monteslu** [comment]
able to get a little further, so I think this is ok.
