### ISSUE TITLE
Devices from second USB bus does not appear in list

### ISSUE THREAD

**Issue by yene** [thegecko/webusb#25]
**Problem:**

* USB device with vendor id 0x0e8d (3725) missing in listUSBDevices()
![shot 2018-07-27 at 19 17 33](https://user-images.githubusercontent.com/63942/43336601-cd177a08-91d1-11e8-89be-712b06f17ec9.png)

* the USB device is listed in Google Chrome

**How to reproduce:**
[JSON export of getDeviceList() ](https://shiro.ch/usb%20devices.json)

**Picture of USB hierarchy**
![shot 2018-07-27 at 18 58 44](https://user-images.githubusercontent.com/63942/43335949-6b21084c-91d0-11e8-85b8-974989370ecb.png)

**Comment by thegecko** [comment]
Do these devices appear if you use the 'node-usb' library directly?

**Comment by yene** [comment]
Yes, it is reported by `node-usb` `usb.getDeviceList()`

**Comment by yene** [comment]
When I connect the GPS Receiver to the other USB bus (a different USB port) he appears in `webusb`.
It seems the second usb bus is filtered out somewhere in the code. I did a quick look but found no location where this could have happened.

Working
![shot 2018-07-29 at 16 08 55](https://user-images.githubusercontent.com/63942/43367220-0842a3c2-934a-11e8-8d17-c02bcf0609b8.png)

Not working
![shot 2018-07-29 at 16 09 09](https://user-images.githubusercontent.com/63942/43367222-09baf830-934a-11e8-80ab-ae9708983396.png)

**Comment by thegecko** [comment]
That is strange. As a test, you can "fool" webusb into listing all devices returned by the libusb adapter by passing an invalid filter:

```javascript
usb.requestDevice({
    filters: [{something: null}]
})
.then(device => {
    ...
});
```

This will at least tell us if its the filters removing your device if it correctly appears in that list.
