### ISSUE TITLE
getDevices not spec-compliant

### ISSUE THREAD

**Issue by dsanders11** [thegecko/webusb#55]
May create a PR for this at some point, but in the mean time creating an issue.

The current implementation of `getDevices` doesn't follow the [steps in the spec](https://wicg.github.io/webusb/#dom-usb-getdevices).

The main effect of this is that it will return all devices in `allowedDevices`, which is incorrect, as this will include devices not connected to the system. This means after disconnecting a device, `getDevices` will still list it, but `open` will throw an error.

**Comment by thegecko** [comment]
Now deleting disconnected devices from the cache
