### ISSUE TITLE
Parameters of USBControlTransferParameters come from?

### ISSUE THREAD

**Issue by GanZhiXiong** [thegecko/webusb#56]
![image](https://user-images.githubusercontent.com/27394631/65762225-1dccb180-e153-11e9-8386-30a5aaf9ae3b.png)

 Where do the values in the red box of the screenshot come from?
requestType, recipient, request, value, index, I'm just writing these arbitrary parameters, so I don't know how to write these parameters?

**Comment by thegecko** [comment]
It's from the usb specification.

http://www.jungo.com/st/support/documentation/windriver/802/wdusb_man_mhtml/node55.html
