### ISSUE TITLE
Can this api be used to detect USB plug/unplug?

### ISSUE THREAD

**Issue by tak40548798** [thegecko/webusb#72]
Can this api be used to detect USB plug/unplug?

**Comment by thegecko** [comment]
Yes, it follows the [WebUSB spec](https://wicg.github.io/webusb/#enumeration) which outlines `onconnect` and ondisconnect` events:

https://github.com/thegecko/webusb/blob/183e468bb5b9f6e899636c434d7aee689c8511fe/examples/url.js#L45

However, if you just want to detect usb devices in node and don't need it to look like WebUSB, I'd recommend using the [node-usb](https://github.com/tessel/node-usb#usbdetection) or [usb-detection](https://github.com/MadLittleMods/node-usb-detection) libraries.
