### ISSUE TITLE
support for allowing all devices

### ISSUE THREAD

**Issue by pelikhan** [thegecko/webusb#82]
In order to enable headless scenario, it would be nice to allow any device matching the filters.

**Comment by thegecko** [comment]
I believe passing options with an empty filter array matches all devices, the same as in the browser.

For a headless scenario, you need a function to select the device, this can be achieved by implementing your own `devicesFound` function, see [this example](https://github.com/thegecko/webusb/blob/master/examples/selector.js).

**Comment by pelikhan** [comment]
I was specifically thinking about the getDrvices function (https://github.com/thegecko/webusb/blob/d800c8103ca18d04264551b86eb0e05fb47a970a/src/usb.ts#L214). Unlike in the browser, I would like to override the behavior and allow any device matching a filter (if that makes sense)

________________________________

**Comment by pelikhan** [comment]
Since the allowed list is not serialized, the behavior is different from the browser, which remembers. My scenario was to use webusb to build a jacdac node-red node; thus in a headless environment.

I have solded it by calling requestDevices from getDevices.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
