### ISSUE TITLE
Feature request: Ability to specify device timeouts

### ISSUE THREAD

**Issue by freshollie** [thegecko/webusb#86]
I was getting Control Transfer In timeouts. Couldn't see anything in the documentation here, but found the docs for `node-usb` and realised I had to set the default timeout on the `Device` class in `node-usb`.

Seems a bit hacky, but all worked when I did that.

```typescript
import { USB } from "webusb";
import { Device as NativeUSBDevice } from "usb";
NativeUSBDevice.prototype.timeout = 60000;

const usb = new USB({
  devicesFound: async (devices) => {
    ...
  },
});
```

Would be good if a default timeout could be passed in as the options to the `USB` constructor. Otherwise, I hope others find this hack useful :)

**Comment by thegecko** [comment]
This would be a great addition to the `USBOptions` object and would need to be passed down to the adapter.

We are currently [merging this library with `node-usb`](https://github.com/node-usb/node-usb/tree/v2.0.0), so happy to consider an addition there.

If it's needed here, feel free to create a PR and I'll merge it.

**Comment by freshollie** [comment]
Cool. Nice to see this is now merged with `node-usb`. I still think an option on `WebUSB` so set the default timeout for all devices, but I'll create a PR for that if I have time.
